#!/usr/bin/python
'''
Created on 7. apr. 2015

@author: Stian Strom Anderssen
'''
import argparse
import sys
from createmachine import * 
parser=argparse.ArgumentParser(description="Scale and deploy a webserver")
parser.add_argument('-l','--list', help='List all webservers running', required=False, action='store_true')
parser.add_argument('-d','--delete', help='Delete a specific server', required=False)
parser.add_argument('-s','--start', help='Start monitoring service', required=False, action='store_true')
parser.add_argument('-g','--graphs', help='Generate graphs from files generated in the reports directory ', required=False, action='store_true')
parser.add_argument('-f','--flush',  help='Flush all data generated by the program',required=False, action='store_true')
parser.add_argument('-e','--email',  help='Send stats by email to a given emailaddress',required=False, action='store_true')
parser.add_argument('--stop',  help='Exit program',required=False, action='store_true')
args=parser.parse_args()
run = MachineTasks()
if args.list:
    run.createHostList()
    run.initializeAndFetch()
elif args.delete : 
    run.initializeAndFetch()
    run.deleteMachine(args.delete)
elif args.start : 
    run.initializeAndFetch()
    run.createHostList()
    run.checkPerformance()
elif args.graphs : 
    run.draw()
elif args.flush : 
    run.deleteGraphsAndData()
elif args.email : 
    run.initializeAndFetch()
    run.sendGraphsPerEmail()
elif args.stop: 
    print "Exiting program"
    sys.exit(0)


